.PHONY: clean All

All:
	@echo "----------Building project:[ mmm - Debug ]----------"
	@cd "mmm" && $(MAKE) -f  "mmm.mk"
clean:
	@echo "----------Cleaning project:[ mmm - Debug ]----------"
	@cd "mmm" && $(MAKE) -f  "mmm.mk" clean
